### ISSUE TITLE
"Tags" not working in AWS::CloudFormation::StackSet 

### ISSUE THREAD

**Issue by aryak007** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#30]
The support of list of `tag` for the AWS::CloudFormation::StackSet is present as mentioned in the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#cfn-cloudformation-stackset-tags).

If presented with an array of tags:
```
Tags: 
        - Key: "key1"
          Value: "value1"
        - Key: "key2"
          Value: "value2"
```
It fails with the error message:
```
"Properties validation failed for resource stacksetname with message:\n#: #: only 1 subschema matches out of 2\n#/Tags/1/Key: failed validation constraint for keyword [pattern]"
```
