### ISSUE TITLE
CloudFormation registry resources

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#42]
I'm unclear on the plans for CloudFormation resource types representing registry types. The PR for `AWS::CloudFormation::ResourceVersion`, #4, was merged in August, but is not yet part of the [public CloudFormation resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_CloudFormation.html). The PR for `AWS::CloudFormation::ModuleVersion` #32 was merged in December and is available. There's now a PR merged for `AWS::CloudFormation::TypeVersion` #39.

I believe strongly that _types_ in the registry (resource, module, ...) need separate CloudFormation resource types. A module is not the same as a resource provider. I appreciate that `AWS::CloudFormation::TypeVersion` will provide a backstop when new registry types are rolled out, so that people can use them immediately, but this should _not_ preempt the creation of dedicated resource types for new registry types.

When is `AWS::CloudFormation::ResourceVersion` going to come out? Can you confirm that the plan is to have resource types corresponding to registry types, and not to just dump `::TypeVersion` on customers and leave it at that?

**Comment by benkehoe** [comment]
To put this in more concrete terms, what sense does it make to have a `Type` CloudFormation resource type _that has its own property called [`Type`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/blob/efaf2776d921643a6f9c2bbf1efe1b217a51dd9c/aws-cloudformation-typeversion/aws-cloudformation-typeversion.json#L105)?_

Can you really argue that this template
```yaml
Resources:
  MyResource:
    Type: AWS::CloudFormation::TypeVersion
    Properties:
      Type: RESOURCE
      TypeName: Custom::Custom::MyResource
      ...

  MyModule:
    Type: AWS::CloudFormation::TypeVersion
    Properties:
      Type: MODULE
      TypeName: Custom::Custom::MyModule
      ...
```

is better for customers than this one?

```yaml
Resources:
  MyResource:
    Type: AWS::CloudFormation::ResourceTypeVersion
    Properties:
      TypeName: Custom::Custom::MyResource
      ...

  MyModule:
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      TypeName: Custom::Custom::MyModule
      ...
```
