### ISSUE TITLE
Custom Version for Cloud Formation Registry modules

### ISSUE THREAD

**Issue by bhvkrishna90** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#64]
Lets say I have two modules in cloud formation registry:

organization::service::portcheck::MODULE with Versions 1, 2(Default version) and 3.

organization::service::iamcheck::MODULE with Versions 1(Default version) and 2.

Now want to write template.yml with below.

```
Resources:
  portcheckmodule: 
    Type: "organization::service::portcheck::MODULE"
  iamcheckmodule:
    Type: "organization::service::iamcheck::MODULE"

```

In the above example how can I define portcheck with version 3 and iamcheck with version 2 with in the template yml file.
Also how can I define custom version for the modules.
